spring.application.name=Easymype

spring.datasource.url=jdbc:postgresql://${DB_Host:postgres}:${DB_Port:5432}/${DB_Name:easymype_bd}
spring.datasource.username=${DB_User:postgres}
spring.datasource.password=${DB_Password:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

app.jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
app.jwt.expiration=${JWT_EXPIRATION:86400000}

app.cors.allowed-origins= ${app.cors.allowed-origins:http://localhost:5173,http://localhost:3000}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true